description: "Generalization arises with a balanced representation space."
url: "https://la0ka1.github.io"
baseurl: "/Diffusion_Rep_Gen_test"
repository: "la0ka1/Diffusion_Rep_Gen_test"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"   # try: "air", "dark", "mint", "sunrise"

plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM

author:
  name: "YOUR NAME"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      toc: false
      toc_sticky: false
